services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - data:/data/
    environment:
      DATABASE_PATH: /data/db/sand-track.sqlite
      UPLOAD_FOLDER: /data/upload
      GUNICORN_PORT: 3000
      GUNICORN_HOST: 0.0.0.0
      SECRET_KEY_FILE: /run/secrets/secret_key
    secrets:
      - secret_key
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/tmp/
      o: bind
secrets:
  secret_key:
    file: ./secret_key.txt
