services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - db_data:/data/
      - upload_data:/tmp/uploads
    environment:
      DATABASE_PATH: /data/db/sand-track.sqlite
      GUNICORN_PORT: 3000
      SECRET_KEY_FILE: /run/secrets/secret_key
    secrets:
      - secret_key
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/tmp/database/
      o: bind
  upload_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/tmp/upload/
      o: bind
secrets:
  secret_key:
    file: ./secret_key.txt
