# fly.toml app configuration file generated for sand-track on 2025-04-15T14:37:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sandtrack'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[env]
  GUNICORN_HOST = '0.0.0.0'
  GUNICORN_PORT = 3000
  DATABASE_PATH = '/data/db/sand-track.sqlite'
  UPLOAD_FOLDER = '/data/upload'

[mounts]
  source = "sandtrack"
  destination = "/data"
  initial_size = "5gb"
