"""add task.submissions_closed

Revision ID: c7f86eb44c29
Revises: 03b287ed21da
Create Date: 2025-06-17 14:59:16.458558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f86eb44c29'
down_revision = '03b287ed21da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submissions_closed', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('submissions_closed')

    # ### end Alembic commands ###
