name: version
on:
  pull_request:
permissions:
  contents: write
jobs:
  version:
    name: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - run: |-
          sed -i 's/\(version = "[0-9]*\.[0-9]*\.\)[0-9]*"/\1${{github.run_number}}"/' pyproject.toml
          new_version=$(grep version pyproject.toml | grep -o '[0-9]*\.[0-9]*\.[0-9]*')
          echo "bumping version to ${new_version}"
          git config --global user.email "gerstle@gmail.com"
          git config --global user.name "casey-bot"
          
          git diff --quiet || (git add pyproject.toml && git commit -m "bump version number to ${new_version}")
          git push
          
